### ISSUE TITLE
Logging formatter issue to remove new lines

### ISSUE THREAD

**Issue by KohliDev** [vmware/liota#124]
Logs are not readable and __/n__ appears everywhere in case of error traceback. This issue occurs after the PR #120 merge, needs to be resolved before Next Liota release:

2017-05-05 12:34:43 UTC 5966 ERROR [MainThread] liota.lib.transports.web_socket.connect_soc(60) - Traceback (most recent call last):__\n__  File "build/bdist.linux-x86_64/egg/liota/lib/transports/web_socket.py", line 58, in connect_soc__\n__    self.WebSocketConnection()__\n__  File "build/bdist.linux-x86_64/egg/liota/lib/transports/web_socket.py", line 71, in WebSocketConnection__\n__    if self.identity.root_ca_cert:__\n__AttributeError: 'bool' object has no attribute 'root_ca_cert'__\n__
2017-05-05 12:41:54 UTC 5994 INFO [MainThread] liota.lib.utilities.utility.setup_logging(242) - created logger with /etc/liota/conf/logging.json
2017-05-05 12:41:54 UTC 5994 INFO [MainThread] liota.lib.utilities.utility.get_disk_name(140) - Disk name is : fd0
2017-05-05 12:41:54 UTC 5994 ERROR [MainThread] liota.lib.transports.web_socket.connect_soc(60) - Traceback (most recent call last):__\n__  File "build/bdist.linux-x86_64/egg/liota/lib/transports/web_socket.py", line 58, in connect_soc__\n__    self.WebSocketConnection()__\n__  File "build/bdist.linux-x86_64/egg/liota/lib/transports/web_socket.py", line 71, in WebSocketConnection__\n__    if self.identity.root_ca_cert:__\n__AttributeError: 'bool' object has no attribute 'root_ca_cert'__\n__
2017-05-05 12:59:22 UTC 6023 INFO [MainThread] liota.lib.utilities.utility.setup_logging(242) - created logger with /etc/liota/conf/logging.json
2017-05-05 12:59:22 UTC 6023 INFO [MainThread] liota.lib.utilities.utility.get_disk_name(140) - Disk name is : fd0
2017-05-05 12:59:22 UTC 6023 ERROR [MainThread] liota.lib.transports.web_socket.connect_soc(60) - Traceback (most recent call last):__\n__  File "build/bdist.linux-x86_64/egg/liota/lib/transports/web_socket.py", line 58, in connect_soc__\n__    self.WebSocketConnection()__\n__  File "build/bdist.linux-x86_64/egg/liota/lib/transports/web_socket.py", line 67, in WebSocketConnection__\n__    self.ws = create_connection(self.host, enable_multithread=True,__\n__AttributeError: WebSocket instance has no attribute 'host'__\n__
2017-05-05 13:02:19 UTC 6052 INFO [MainThread] liota.lib.utilities.utility.setup_logging(242) - created logger with /etc/liota/conf/logging.json
2017-05-05 13:02:19 UTC 6052 INFO [MainThread] liota.lib.utilities.utility.get_disk_name(140) - Disk name is : fd0
2017-05-05 13:02:19 UTC 6052 ERROR [MainThread] liota.lib.transports.web_socket.connect_soc(60) - Traceback (most recent call last):__\n__  File "build/bdist.linux-x86_64/egg/liota/lib/transports/web_socket.py", line 58, in connect_soc__\n__    self.WebSocketConnection()__\n__  File "build/bdist.linux-x86_64/egg/liota/lib/transports/web_socket.py", line 68, in WebSocketConnection__\n__    sslopt={"cert_reqs": ssl.CERT_NONE})__\n__  File "/usr/local/lib/python2.7/dist-packages/websocket_client-0.37.0-py2.7.egg/websocket/_core.py", line 489, in create_connection__\n__    websock.connect(url, **options)__\n__  File "/usr/local/lib/python2.7/dist-packages/websocket_client-0.37.0-py2.7.egg/websocket/_core.py", line 219, in connect__\n__    self.handshake_response = handshake(self.sock, *addrs, **options)__\n__  File "/usr/local/lib/python2.7/dist-packages/websocket_client-0.37.0-py2.7.egg/websocket/_handshake.py", line 67, in handshake__\n__    status, resp = _get_resp_headers(sock)__\n__  File "/usr/local/lib/python2.7/dist-packages/websocket_client-0.37.0-py2.7.egg/websocket/_handshake.py", line 123, in _get_resp_headers__\n__    raise WebSocketBadStatusException("Handshake status %d", status)__\n__WebSocketBadStatusException: Handshake status 404__\n__

**Comment by pmasrani** [comment]
Issue was incorrect usage of log.error to log the stacktrace. log.exception should be used for printing stacktrace. Corrected in review: https://github.com/vmware/liota/pull/125

**Comment by KohliDev** [comment]
Okay. I would also suggest reviewing the multiple places where log.error is used in the liota codebase in case we require to change it to log.exception as it fixes the issue.

**Comment by pmasrani** [comment]
traceback module is used only in this location.

**Comment by KohliDev** [comment]
Issue occurs at multiple places in log files:


2017-05-18 19:27:54 PDT 5721 INFO [PackageThread] liota.core.package_manager.run(355) - Got message in package messenger queue: list pkg
2017-05-18 19:27:54 PDT 5721 WARNING [PackageThread] liota.core.package_manager._cmd_handler_list(257) - List of packages - __\n__	
2017-05-18 19:28:18 PDT 5721 INFO [PackageThread] liota.core.package_manager.run(355) - Got message in package messenger queue: load edge_systems/dell5k/edge_system 626d4caddc37bb7958e5a491126733d2bc0f6aa3
2017-05-18 19:28:18 PDT 5721 INFO [PackageThread] liota.core.package_manager._package_load(567) - Loaded package file: /etc/liota/packages/edge_systems/dell5k/edge_system.py (626d4caddc37bb7958e5a491126733d2bc0f6aa3)
2017-05-18 19:28:18 PDT 5721 INFO [PackageThread] liota.lib.utilities.utility.get_uuid(108) - resource: EdgeSystem-Name  uuid=113294af-1770-547d-9b80-0cbe3cae02e1
2017-05-18 19:28:18 PDT 5721 INFO [PackageThread] liota.core.package_manager._package_load(644) - Package class from module edge_systems/dell5k/edge_system is initialized
2017-05-18 19:28:32 PDT 5721 INFO [PackageThread] liota.core.package_manager.run(355) - Got message in package messenger queue: list pkg
2017-05-18 19:28:32 PDT 5721 WARNING [PackageThread] liota.core.package_manager._cmd_handler_list(257) - List of packages - __\n__	edge_systems/dell5k/edge_system


2017-05-19 00:18:26 UTC 1133 DEBUG [PackageThread] liota.core.device_discovery._get_config_from_file(149) - endpoint_list:(disc_msg_pipe : /etc/liota/packages/dev_disc/discovery_messenger.fifo)__\n__
2017-05-19 00:18:26 UTC 1133 DEBUG [PackageThread] liota.core.device_discovery._get_config_from_file(158) - type_key_map:(Press64 : serial)__\n__
2017-05-19 00:18:26 UTC 1133 DEBUG [PackageThread] liota.core.device_discovery._get_config_from_file(158) - type_key_map:(LM35 : SN)__\n__
2017-05-19 00:18:26 UTC 1133 DEBUG [PackageThread] liota.core.device_discovery._get_config_from_file(158) - type_key_map:(Banana23 : serial)__\n__
2017-05-19 00:18:26 UTC 1133 DEBUG [PackageThread] liota.core.device_discovery._get_config_from_file(158) - type_key_map:(Apple56 : SN)__\n__
2017-05-19 00:18:26 UTC 1133 DEBUG [PackageThread] liota.core.device_discovery._get_config_from_file(170) - type_dcc_map:(Press64 : ['iotcc_mqtt', 'iotcc'])__\n__
2017-05-19 00:18:26 UTC 1133 DEBUG [PackageThread] liota.core.device_discovery._get_config_from_file(170) - type_dcc_map:(LM35 : ['graphite', 'iotcc_mqtt', 'iotcc'])__\n__
2017-05-19 00:18:26 UTC 1133 DEBUG [PackageThread] liota.core.device_discovery._get_config_from_file(170) - type_dcc_map:(Banana23 : ['iotcc'])__\n__
2017-05-19 00:18:26 UTC 1133 DEBUG [PackageThread] liota.core.device_discovery._get_config_from_file(170) - type_dcc_map:(Apple56 : ['iotcc_mqtt', 'iotcc'])__\n__
2017-05-19 00:18:26 UTC 1133 DEBUG [PackageThread] liota.core.device_discovery._get_config_from_file(172) - type_tuple_key_dcc_pkg:(Press64 : ('serial', ['iotcc_mqtt', 'iotcc']))__\n__
2017-05-19 00:18:26 UTC 1133 DEBUG [PackageThread] liota.core.device_discovery._get_config_from_file(172) - type_tuple_key_dcc_pkg:(LM35 : ('SN', ['graphite', 'iotcc_mqtt', 'iotcc']))__\n__
2017-05-19 00:18:26 UTC 1133 DEBUG [PackageThread] liota.core.device_discovery._get_config_from_file(172) - type_tuple_key_dcc_pkg:(Banana23 : ('serial', ['iotcc']))__\n__
2017-05-19 00:18:26 UTC 1133 DEBUG [PackageThread] liota.core.device_discovery._get_config_from_file(172) - type_tuple_key_dcc_pkg:(Apple56 : ('SN', ['iotcc_mqtt', 'iotcc']))__\n__

**Comment by KohliDev** [comment]
@pmasrani This issue exist in liota-0.3 beta release. Any progress on this issue?

**Comment by pmasrani** [comment]
It is not a good practice to have multi-line logs, except for stack traces as those logs can't be parsed well by log parsers. It is up to individual module owner to make sure they add logs in good format, without using \n. Assigning to Winnie to take a look at package manager and device discovery logs.

**Comment by pmasrani** [comment]
@winniex1 Can you please make sure that logs in Package Manager and Device discovery modules do not use \n.

**Comment by winniex1** [comment]
Ok. I’ll have a look on it.

**Comment by KohliDev** [comment]
@winniex1 & @bfrggit Can you please look into this issue?

**Comment by winniex1** [comment]
@vaibhav   remembered we said to check in after master is stable status.
@ bfrggit  you may fix package manager part. I’ll fix device discovery

**Comment by bfrggit** [comment]
@winniex1 Okay. I will change the package manager. Just change the output format to remove the newlines I guess?

**Comment by bfrggit** [comment]
> Okay. I will change the package manager. Just change the output format to remove the newlines I guess?

For the package manager stats -

I just mentioned this to @pmasrani. It seems that we do not want to simply change `\n` to spaces since "stats are still unreadable" in that way.

@pmasrani proposed two potential fixes:

1. Output stats back to where the command is invoked. This requires some changes, since we may need a different pipe (or similar) to get those info back. The `liotapkg.sh` script also needs to be changed so it listens to that "different pipe" after command is written.

2. Quicker fix: Create a different log file somewhere else, that contains package manager's logs, or perhaps just package manager's stat outputs. This requires changes in package manager only in Liota, but requires additional info in Liota config. Now we only have one Liota log file that contains everything. By doing this, we are starting different log files.

If this is not urgent before VMworld, we may want to discuss a little before I or anyone else actually make the changes.

**Comment by KohliDev** [comment]
Any update on this issue as this needs to be fixed before we roll out final version of Liota.
